services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: paymelah-bot
    restart: unless-stopped
    env_file:
      - src/.env
    volumes:
      - ./src:/app:ro
      - ./src/logs:/app/logs
    networks:
      - paymelah-network

networks:
  paymelah-network:
    driver: bridge