"""initial_migration_with_tz

Revision ID: 1dfa14ced14f
Revises:
Create Date: 2025-12-29 14:32:56.098190

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1dfa14ced14f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='Telegram user ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Telegram username'),
    sa.Column('first_name', sa.String(length=255), nullable=True, comment="User's first name"),
    sa.Column('last_name', sa.String(length=255), nullable=True, comment="User's last name"),
    sa.Column('preferred_currency', sa.String(length=3), nullable=False, comment="User's preferred currency"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment="User's creation timestamp"),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment="User's last update timestamp"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Group ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Group name chosen by the user'),
    sa.Column('description', sa.Text(), nullable=True, comment='Additional description of the group'),
    sa.Column('default_currency', sa.String(length=3), nullable=False, comment="Default currency for the group's expenses"),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='User who created the group'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Group creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Group last update timestamp'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Expense ID'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='ID of the group the expense belongs to'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the expense'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Amount of the expense in the currency of this specific expense'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency of the expense'),
    sa.Column('payer_id', sa.BigInteger(), nullable=True, comment='ID of the user who paid for the expense'),
    sa.Column('expense_date', sa.Date(), nullable=False, comment='Date that the expense was incurred'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Optional category of the expense'),
    sa.Column('split_type', sa.Enum('EQUAL', 'EXACT', 'PERCENTAGE', 'CUSTOM', name='expensesplittype', native_enum=False, length=20), nullable=False, comment='Type of split for the expense'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='ID of the user who created the expense'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Expense creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Expense last update timestamp'),
    sa.Column('is_settled', sa.Boolean(), nullable=False, comment='Whether the expense has been settled'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Group member ID'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='ID of the group the member belongs to'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID of the user who is a member of the group'),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', 'OWNER', name='groupmemberrole', native_enum=False, length=20), nullable=False, comment='Role of the user in the group'),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the user joined the group'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Payment ID'),
    sa.Column('from_user_id', sa.BigInteger(), nullable=True, comment='ID of the user who sent the payment'),
    sa.Column('to_user_id', sa.BigInteger(), nullable=True, comment='ID of the user who received the payment'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='ID of the group the payment belongs to'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Amount of the payment'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency of the payment'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Optional description of the payment'),
    sa.Column('payment_date', sa.Date(), nullable=False, comment='Date of the payment'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Payment creation timestamp'),
    sa.Column('expense_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of expense IDs this payment settles'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Expense participant ID'),
    sa.Column('expense_id', sa.Integer(), nullable=False, comment='ID of the expense the participant belongs to'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID of the user who is a participant in the expense'),
    sa.Column('share_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Amount the participant owes or has paid'),
    sa.Column('split_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage of the expense the participant owes or has paid'),
    sa.Column('is_settled', sa.Boolean(), nullable=False, comment='Whether the participant has paid their share'),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the participant paid their share'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_participants')
    op.drop_table('payments')
    op.drop_table('group_members')
    op.drop_table('expenses')
    op.drop_table('groups')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
